version: '3.8'
volumes:
  harvester_postgres:
    external: false
services:
  harvester-postgres:
    container_name: harvester_postgres
    image: postgres:16-alpine
    volumes:
      - harvester_postgres:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: ${HARVESTER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${HARVESTER_POSTGRES_PASSWORD}
      POSTGRES_DB: "harvester"
    networks:
      - harvester-network
  harvester-api:
    container_name: harvester_api
    build:
      context: .
      dockerfile: Dockerfile
      target: spice-harvester-api
    image: spice-harvester-api:latest
    ports:
      - "127.0.0.1:8087:8081" # also change PORT and PROXY_PASS env if you want to change port here
    restart: unless-stopped
    depends_on:
      - harvester-postgres
    environment:
      PORT: 8081
      LOG_LEVEL: "INFO"
      POSTGRES_URI: ${HARVESTER_POSTGRES_URI}
      TOKEN: ${HARVESTER_API_TOKEN}
      LITE_SERVERS: ${HARVESTER_LITE_SERVERS}
      RECIPIENT: ${HARVESTER_RECIPIENT}
#     Optional parameters:
      KEY: ${HARVESTER_KEY}
      JETTONS: ${HARVESTER_JETTONS}
      WEBHOOK_ENDPOINT: ${HARVESTER_WEBHOOK_ENDPOINT}
      PAYMENT_PREFIXES: ${HARVESTER_PAYMENT_PREFIXES}
    networks:
      - harvester-network
  harvester-reverse-proxy:
    container_name: harvester_reverse_proxy
    image: ton-reverse-proxy:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: ton-reverse-proxy
    ports:
      - "10391:9306/udp" # also change PORT env if you want to change port here
    restart: unless-stopped
    environment:
      PROXY_PASS: "http://harvester_api:8081/"
      KEY: ${HARVESTER_KEY}
      LISTEN_IP: "0.0.0.0"
      NETWORK_CONFIG_URL: "https://ton.org/global.config.json"
      PORT: 9306
#     Optional parameters:
      EXTERNAL_IP: ${TON_PROXY_EXTERNAL_IP}
    networks:
      - harvester-network

networks:
  harvester-network:
    driver: bridge
