###
POST {{host}}/tonpay/private/api/v1/invoice
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "amount": "100000000",
  "currency": "TON",
  "private_info": {
    "order_number": 123
  },
  "metadata": {
    "merchant_name": "Coffee shop",
    "merchant_url": "https://coffee.com/",
    "mcc_code": 5462,
    "goods": [
      {"name": "Latte 300ml"}
    ]
  },
  "life_time": 3000
}

###
GET {{host}}/tonpay/private/api/v1/invoices/{{id}}
Authorization: Bearer {{token}}

###
GET {{host}}/tonpay/public/api/v1/invoices/{{id}}

###
POST {{host}}/tonpay/private/api/v1/invoices/{{id}}/cancel
Authorization: Bearer {{token}}

###
GET {{host}}/tonpay/private/api/v1/invoices
Authorization: Bearer {{token}}

###
GET {{host}}/tonpay/public/manifest
