###
POST {{host}}/tonpay/private/api/v1/invoice
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "amount": "100000000",
  "currency": "TON",
  "description": "coffee shop",
  "metadata": {
    "merchant_name": "Coffee shop",
    "merchant_url": "https://coffee.com/",
    "mcc_code": 5462,
    "goods": [
      {"name": "Latte 300ml"}
    ]
  },
  "life_time": 3000
}

###
GET {{host}}/tonpay/private/api/v1/invoices/03cfc582-b1c3-410a-a9a7-1f3afe326b3b
Authorization: Bearer {{token}}

###
POST {{host}}/tonpay/private/api/v1/invoices/03cfc582-b1c3-410a-a9a7-1f3afe326b3b/cancel
Authorization: Bearer {{token}}

###
GET {{host}}/tonpay/private/api/v1/invoices
Authorization: Bearer {{token}}
